version: "3"
services:
  frontend:
    build: .
    entrypoint: go-micro-services frontend
    ports:
      - "5000:8080"
    links:
      - jaeger
      - search
      - profile
    depends_on:
      - search
      - profile
  search:
    build: .
    entrypoint: go-micro-services search
    links:
      - geo
      - rate
      - jaeger
    ports:
      - "8091:8080"
  profile:
    build: .
    entrypoint: go-micro-services profile
    links:
      - geo
      - rate
      - jaeger
    ports:
      - "8092:8080"
  geo:
    build: .
    entrypoint: go-micro-services geo
    links:
      - jaeger
    ports:
      - "8093:8080"
  rate:
    build: .
    entrypoint: go-micro-services rate
    links:
      - jaeger
    ports:
      - "8094:8080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
